### ISSUE TITLE
Problem running the wrapper

### ISSUE THREAD

**Issue by alexandreSchenberg** [exander77/xSDM-python-wrapper#1]
Hello, when I run it through: python pysdx path to the sdx file/sdxfile.sdx
I receive: Traceback (most recent call last):
  File "pysdx", line 4, in <module>
    import requests
ImportError: No module named requests

What 's going on? Thanks

**Comment by exander77** [comment]
Exactly what is written. You don't have python module named requests installed.

**Comment by alexandreSchenberg** [comment]
Ok, solved it. There is a way to stop and then latter resume the download ?

**Comment by exander77** [comment]
No, there is currently no such method.
